#!/usr/local/bin/perl
use File::Compare;

$noArgs=scalar(@ARGV);
$tmpDir="./";
print "Operating System =$^O\n" ;


if ($^O eq "linux")
{
  $dataPath="/research/sunburn/dsmft/OBPRM/graphValidationData";
  $makefileName = $dataPath."/Makefile.linux";
 $OS="linux";
}
else {
  if ($^O eq "hpux") {
  $dataPath="/research/sunburn/dsmft/OBPRM/graphValidationData";
  $makefileName = $dataPath."/Makefile.hp";
 $OS="hp";
 }
 else {
  if ($^O eq "solaris") {
  $dataPath="/pub/dsmft3/OBPRM/graphValidationData";
  $makefileName = $dataPath."/Makefile.sun";
 $OS="sun";
 }
 else {
  if ($^O eq "irix") {
  $dataPath="/pub/dsmft3/OBPRM/graphValidationData";
  $makefileName = $dataPath."/Makefile.sgi";
 $OS="sgi";
 }
}

} 
}

$fileName1 = "graph_test_results";
$fileName2 = $dataPath."/valid_graph_test_results";

  print "Making file\n";
 system("cp ../Graph.h .");
# system("./cpG");
 system("make -f Makefile.$OS");
 system("./gexe");
 system("rm Graph.h");

  print "Testing ...\n";
  if( compare("$fileName2","$fileName1")) {
    errorMsg( "$fileName1 differ from  the validation file $fileName2\n");
	system("rm graph_test_results");
	system("rm /graphtest.exe"); 
 }
   

 sendOkMsg();
 printf("Everything seems ok on $OS as of: \n");
 system("date");
	system("rm graph_test_results");
	system("rm graphtest.exe"); 
  
 

sub usage {
 printf("usage: validateOBPRM [-email] [-cvs [temp directory name]]\n");
}

sub errorMsg{
 local($errorNo)=@_;
 print "$errorNo";
 if ($sendMail) {

  #$msg= new Mail::Send Subject=>"Graph.h validation failed on $OS",To=>'gsong@cs.tamu.edu dalel\@unix.tamu.edu';
  #$fh=$msg->open;
  #print $fh "Failed to validate Graph.h on $OS\n";
  #print $fh "Error message was to  $errorNo\n";
  #$fh->close;
 if ( ($OS eq "sun"))  {
 #  open(MAIL ,"|/usr/local/bin/elm -s\"Failed to validate Graph.h on $OS\" gsong\@cs.tamu.edu, amato\@cs.tamu.edu");
    open(MAIL ,"|/usr/local/bin/elm -s\"Failed to validate Graph.h on $OS\" pinga\@cs.tamu.edu");
 }
 else {
 #  open(MAIL ,"|elm -s\"Failed to validate Graph.h on $OS\" gsong\@cs.tamu.edu, amato\@cs.tamu.edu");
    open(MAIL ,"|elm -s\"Failed to validate Graph.h on $OS\" pinga\@cs.tamu.edu");
 }
 #  print MAIL "You can see the error log at SYSTEM_DEPENDENT_LOCATION/obprmValidationData/log\n";
 #  print MAIL "Error message was to  $errorNo\n";
   close(MAIL);
 }
 exit;
}

sub sendOkMsg{
 if ($sendMail) {

  # open(MAIL ,"|elm -s\"OK in validating Graph.h on $OS\" gsong\@cs.tamu.edu, amato\@cs.tamu.edu");
   open(MAIL ,"|elm -s\"OK in validating Graph.h on $OS\" pinga\@cs.tamu.edu");
   print MAIL "Everything is ok on $OS\n";
   close(MAIL);
 }
}
