image: illario/pmpl:latest

stages:
- build
- test
- deploy

build:
  stage: build
  tags:
    - linux
  only:
    - ari-merge
  variables:
    VCPKG_BINARY_CACHE_PATH: $CI_PROJECT_DIR/vcpkg_cache
    VCPKG_ROOT: $CI_PROJECT_DIR/vcpkg
    VCPKG_DIR: /opt/vcpkg/scripts/buildsystems/vcpkg.cmake
  script:
    - cmake -B debug_build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$VCPKG_DIR -DCODE_COVERAGE=ON
#    - cmake --build debug_build
    - cmake --build debug_build --target generate_doxygen_docs
    - cmake --build debug_build --target tests
  timeout: 3 hours
  cache:
    key: vcpkg-cache
    paths:
      - vcpkg_cache/
  artifacts:
    paths:
      - debug_build/.ninja_log
      - debug_build/docs/Doxygen/html

unit-test-job:
  stage: test
  tags:
    - linux
  only:
    - ari-merge
    - release-stage-one
  script:
    - ls

strategy-test-job:
  stage: test
  tags:
    - linux
  only:
    - ari-merge
    - release-stage-one
  script:
    - cd debug_build
    - ./ppl_tests -F BasicTests

publish-doc-job:
  stage: deploy
  tags:
    - linux
  when: manual
  only:
    - ari-merge
    - release-stage-one
  script:
    - ls

create_package:
  stage: deploy
  when: manual
  tags:
    - linux
  script:
    - conan remote add gitlab https://gitlab.engr.illinois.edu/api/v4/projects/25350/packages/conan
    - conan new pmpl/1.0.0 -t
    - conan create . parsol+pmpl+ppl/stable
    - CONAN_LOGIN_USERNAME=conan_pat CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload pmpl/1.0.0@parasol-group+parsol+pmpl/stable --all --remote=gitlab
  environment: production
