image: illario/pmpl:latest

stages:
- build
- test
- deploy

variables:
  VCPKG_BINARY_CACHE_PATH: $CI_PROJECT_DIR/vcpkg_cache
  VCPKG_ROOT: $CI_PROJECT_DIR/vcpkg
  VCPKG_DIR: /opt/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  stage: build
  tags:
    - linux
  only:
    - ari-merge
    - release-stage-one
  script:
    - cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$VCPKG_DIR -DCODE_COVERAGE=ON
#    - cmake --build build
    - cmake --build build --target generate_doxygen_docs
    - cmake --build build --target tests
  timeout: 3 hours
  cache:
    key: vcpkg-cache
    paths:
      - vcpkg_cache/
  artifacts:
    paths:
      - build/.ninja_log
      - build/docs/Doxygen/html

unit-test-job:
  stage: test
  dependencies:
    - build
  tags:
    - linux
  only:
    - ari-merge
    - release-stage-one
  script:
    - cd build
    - ls

strategy-test-job:
  stage: test
  dependencies:
    - build
  tags:
    - linux
  only:
    - ari-merge
    - release-stage-one
  script:
    - cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$VCPKG_DIR -DCODE_COVERAGE=ON
    - cmake --build build --target tests
    - cd build
    - ctest --output-on-failure --output-junit junit.xml
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' '*/vcpkg_installed/*' --output-file coverage.info
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /lines:\s+(\d+\.\d+)\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      junit: build/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml

publish-doc-job:
  stage: deploy
  tags:
    - linux
  when: manual
  only:
    - ari-merge
    - release-stage-one
  script:
    - ls

create_package:
  stage: deploy
  when: manual
  only:
    - ari-merge
    - release-stage-one
  tags:
    - linux
  script:
    - conan remote add gitlab https://gitlab.engr.illinois.edu/api/v4/projects/25350/packages/conan
    - conan new ppl/1.0.1 -t
    - conan create . parasol+pmpl+ppl/stable
    - CONAN_LOGIN_USERNAME=conan_pat CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload ppl/1.0.1@parasol-group+parasol+pmpl+ppl/stable --all --remote=gitlab
  environment: production
