qsub ZTunnel4.Uniform_RRT.0.sh
qsub ZTunnel4.Uniform_RRT.1.sh
qsub ZTunnel4.Uniform_RRT.2.sh
qsub ZTunnel4.Uniform_RRT.3.sh
qsub ZTunnel4.Uniform_RRT.4.sh
qsub ZTunnel4.Uniform_RRT.5.sh
qsub ZTunnel4.Uniform_RRT.6.sh
qsub ZTunnel4.Uniform_RRT.7.sh
qsub ZTunnel4.Uniform_RRT.8.sh
qsub ZTunnel4.Uniform_RRT.9.sh
qsub ZTunnel4.Uniform_RRT.10.sh
qsub ZTunnel4.Uniform_RRT.11.sh
qsub ZTunnel4.Uniform_RRT.12.sh
qsub ZTunnel4.Uniform_RRT.13.sh
qsub ZTunnel4.Uniform_RRT.14.sh
qsub ZTunnel4.Uniform_RRT.15.sh
qsub ZTunnel4.Uniform_RRT.16.sh
qsub ZTunnel4.Uniform_RRT.17.sh
qsub ZTunnel4.Uniform_RRT.18.sh
qsub ZTunnel4.Uniform_RRT.19.sh
qsub ZTunnel4.Uniform_RRT.20.sh
qsub ZTunnel4.Uniform_RRT.21.sh
qsub ZTunnel4.Uniform_RRT.22.sh
qsub ZTunnel4.Uniform_RRT.23.sh
qsub ZTunnel4.Uniform_RRT.24.sh
qsub ZTunnel4.Uniform_RRT.25.sh
qsub ZTunnel4.Uniform_RRT.26.sh
qsub ZTunnel4.Uniform_RRT.27.sh
qsub ZTunnel4.Uniform_RRT.28.sh
qsub ZTunnel4.Uniform_RRT.29.sh
qsub ZTunnel4.Uniform_RRT.30.sh
qsub ZTunnel4.Uniform_RRT.31.sh
qsub ZTunnel4.Uniform_RRT.32.sh
qsub ZTunnel4.Uniform_RRT.33.sh
qsub ZTunnel4.Uniform_RRT.34.sh
qsub ZTunnel4.Uniform_RRT.35.sh
qsub ZTunnel4.Uniform_RRT.36.sh
qsub ZTunnel4.Uniform_RRT.37.sh
qsub ZTunnel4.Uniform_RRT.38.sh
qsub ZTunnel4.Uniform_RRT.39.sh
qsub ZTunnel4.Uniform_RRT.40.sh
qsub ZTunnel4.Uniform_RRT.41.sh
qsub ZTunnel4.Uniform_RRT.42.sh
qsub ZTunnel4.Uniform_RRT.43.sh
qsub ZTunnel4.Uniform_RRT.44.sh
qsub ZTunnel4.Uniform_RRT.45.sh
qsub ZTunnel4.Uniform_RRT.46.sh
qsub ZTunnel4.Uniform_RRT.47.sh
qsub ZTunnel4.Uniform_RRT.48.sh
qsub ZTunnel4.Uniform_RRT.49.sh
