################################################################################
# colors.py
#
# Description: Creates vizmo environment with obstacles colored according to
#  conflicts along a given path.
#
# Usage: Takes in:
#  -a label file (the output file generated by pmpl ending in .pc)
#  -the vizmo environment file which should have its obstacles colored.
#  -an output file location
#
# The program then outputs the input vizmo file with the colors having been
# changed for the conflicting components to red.
#
# NOTE: Component names in the input env file must include a number, e.g.
# Passive
# components/piece0.obj -c(0 1 0 1) ...
################################################################################

import re


# Converts a list of numbers to a string.
def ListToString(l, number):
  if number <= 0:
    return ''

  string = l[0]
  for i in range(1, number):
    string += ' ' + str(l[i])
  return string

# Gets the prefix of the file, i.e. all parts of .env until passive components.
def GetPrefix(infile):
  return infile.read().partition('Passive')[0]

# Reads in a component string and grabs the relevant info.
def ProcessComponent(string):
  nums = []
  while string.strip(' \n\t'):
    nums.append(re.findall('[+-]?\d+\.?\d*', string)[0])
    string = string.split(nums[-1], 1)[1]
  number = int(nums.pop(0).strip('.'))
  color = [nums.pop(0) for i in range(4)]
  pos = [nums.pop(0) for i in range(6)]
  return number, color, pos

# Reads in the component lines as strings and returns lists of defining data.
def GetComponents(infile):
  parts = list(infile.read().split('Passive'))
  parts.pop(0)

  number, color, pos = [], [], []

  for part in parts:
    n, c, p = ProcessComponent(part)
    number.append(n)
    color.append(c)
    pos.append(p)

  return number, color, pos

# Sets the color for conflicting pieces.
def AdjustColors(colors, labelfile):
  indices = [int(i) for i in labelfile.read().strip(' \n\t').split(' ')]
  for index in indices:
    colors[index] = ['1', '0', '0', '1']
  return colors

# Writes a passive component.
def WritePassiveComponent(number, color, pos, out):
  out.write('Passive\ncomponents/' + str(number) + '.obj -c(' + ListToString(color, 4) +
            ') -a(none) ' + ListToString(pos, 6) + '\n\n')

# Writes the output file.
def WriteOutputFile(prefix, comps, out):
  out.write(prefix)
  for comp in comps:
    WritePassiveComponent(comp[0], comp[1], comp[2], out)


def Main():
  # Get arguments
  import argparse
  parser = argparse.ArgumentParser()

  parser.add_argument('-l', '--label-file', required=True, help='path to label file to read')
  parser.add_argument('-e', '--env-file', required=True, help='path to input env file (vizmo version)')
  parser.add_argument('-o', '--output-file', required=True, help='path to output env file')

  args = parser.parse_args()

  # Identify which components should have what colors.
  with open(str(args.env_file), 'r') as infile:
    prefix = GetPrefix(infile)
  with open(str(args.env_file), 'r') as infile:
    numbers, colors, poses = GetComponents(infile)

  # Read in label file.
  with open(str(args.label_file), 'r') as labelfile:
    colors = AdjustColors(colors, labelfile)

  comps = [(i, j, k) for i,j,k in zip(numbers, colors, poses)]

  # Print a new vizmo env.
  with open(str(args.output_file), 'w') as out:
    WriteOutputFile(prefix, comps, out)

if __name__ == '__main__':
  Main()

################################################################################
# END OF FILE
################################################################################

