name: Compile Issue
description: Issues related to compiling clean versions of ppl. 
title: "[Compile Issue] DESCRIPTIVE SUMMARY"
labels: [Compile]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search through the issues to see if an issue already exists. 
      options:
        - label: I have searched for existing issues on the ppl issues page.
          required: True
  - type: input
    attributes:
      label: OS used
      description: What OS are you using?
      placeholder: Ubuntu 22.04 (WSL), Mac Sierra, 
    validations:
      required: True
  - type: input
    attributes:
      label: Branch
      description: What branch are you on?
      placeholder: release-stage-two
    validations:
      required: True
  - type: textarea
    attributes:
      label: Commands run
      description: What commands did you run? Please list ALL commands. 
      placeholder: You can use triple backticks ` to help format nicely. 
    validations:
      required: True
  - type: textarea
    attributes:
      label: Errors
      description: Please paste the error you got. 
      placeholder: Please use triple backticks ` for better formatting. 
    validations:
      required: True
      
      
