# Copyright (c) 2000-2009, Texas Engineering Experiment Station (TEES), a
# component of the Texas A&M University System.
#
# All rights reserved.
#
# The information and source code contained herein is the exclusive
# property of TEES and may not be disclosed, examined or reproduced
# in whole or in part without explicit written authorization from TEES.


# a dummy redirect to make sure GNU make is installed and used
# (GNU make will default to GNUmakefile... this is for non-GNU make)

default:
	echo "Redirecting to GNU make (gmake)..."
	gmake

# EOF
