/*
// Copyright (c) 2000-2009, Texas Engineering Experiment Station (TEES), a
// component of the Texas A&M University System.

// All rights reserved.

// The information and source code contained herein is the exclusive
// property of TEES and may not be disclosed, examined or reproduced
// in whole or in part without explicit written authorization from TEES.
*/


/* generated by make_and_test.pl */

#ifndef MATRIX_ATTR_H
#define MATRIX_ATTR_H

#define NUMTYPE double
#define SHAPE rectangle<>
#define STORAGE dense<>
#define ORIEN row_major
#define TESTNAME "banded_banded_view_column_major_complex"

#endif /* MATRIX_ATTR_H */
