# $Id$
#------------------------------------------------------
# Make your own and use it or use the one in BASELINE
#------------------------------------------------------

# -- for dynamic shared object library libobprm.so
   OBPRMLIB_DIR = .
   OBPRMLIB     = -L${OBPRMLIB_DIR} -lobprm

#------------------------------------------------------
# Basic defns; do not change
#------------------------------------------------------
 MATHLIB   = -lm
 STL_INCL  = -I/pub/dsmft/STL

#------------------------------------------------------
# collision detection packages available
#------------------------------------------------------

 CSTK_DIR  = /home/g0s4525/ParallelCode/CD-libs/CSTK/
 CSTKLIB_DIR  = /home/g0s4525/ParallelCode/CD-libs/CSTK/lib
 CSTKLIB      = -L${CSTKLIB_DIR} -lcstk
 CSTK_INCL    = -I${CSTK_DIR}/include

 VCLIP_DIR     = /home/g0s4525/ParallelCode/CD-libs/VCLIP
 VCLIPLIB_DIR  = ${VCLIP_DIR}/lib
 VCLIPLIB      = -L${VCLIPLIB_DIR} -lvclip
 VCLIP_INCL    = -I${VCLIP_DIR}/include


#-----------------------------------------------------------------------------
# Defines for various types of executables
#	VERBOSE  for printing out all kinds of babble for debugging
#       INTERMEDIATE_FILES for creating intermediate "*.path" files
#--------------------------------------------------------------------------
   ADEFS = -DVERBOSE=0 -DINTERMEDIATE_FILES=0 -DCHECKIFSAMECC=0 -DNO_CD_USE #-DUSE_CSTK #-DUSE_VCLIP 

### DEFS = ${ADEFS} -DQUIETGRAPH -DQUIET
    DEFS = ${ADEFS} -D QUIET

showdefs :: 
	echo "${DEFS}";


 AFLAGS    = -I. ${STL_INCL} ${CSTK_INCL} ${VCLIP_INCL} ${RAPID_INCL} ${PQP_INCL} ${DEFS}

#-----------------------------------------------------------------------------
# Choose a compiler & its options
#--------------------------------------------------------------------------
 CC = CC
#CC = /pub/gnu_sgi/bin/g++

CXX = CC

# -- for development on TERMINATOR (can't seem to use it better due to cstk)
   OPTS = -64 -O2 -mips4  -exceptions
#  OPTS = -o32 -O1 -show -ptv 
# -- optimized (our O2's) (slow_compile/good_code) --
#  OPTS =  -o32 -O2 -OPT:Olimit=0 -show

#  DEPS = 
   DEPS = -MDupdate Dependencies 

# -- warnings (default, full, none) --
#  CWARNS = 
#  CWARNS = -fullwarn
   CWARNS = -w

CFLAGS     = $(OPTS) $(AFLAGS) $(DEPS) $(CWARNS)
CXXFLAGS   = $(CFLAGS) 
DSOFLAGS   = $(CFLAGS) -shared -no_unresolved


#-----------------------------------------------------------------------------
# Build 
#--------------------------------------------------------------------------

#--------------------------------------------------------------------
deps: 
	touch Dependencies

libs: objs libobprm.so 

libobprm.so: $(OBJS)
	$(CXX) -o libobprm.so $(DSOFLAGS) $(OBJS)


#--------------------------------------------------------------------
obprm: main_obprm.cpp  libs
	$(CXX) $(CXXFLAGS) -o obprm \
           -rpath $(OBPRMLIB_DIR):$(CSTKLIB_DIR):${VCLIPLIB_DIR}:${RAPIDLIB_DIR}:${PQPLIB_DIR} \
                main_obprm.cpp \
		$(OBPRMLIB) $(MATHLIB) #$(CSTKLIB) ${VCLIPLIB} ${RAPIDLIB} ${PQPLIB}
	rm -f main_obprm.o

#--------------------------------------------------------------------
query: main_query.cpp libs
	$(CXX) $(CXXFLAGS) -o query \
           -rpath $(OBPRMLIB_DIR):$(CSTKLIB_DIR):${VCLIPLIB_DIR}:${RAPIDLIB_DIR}:${PQPLIB_DIR} \
                main_query.cpp \
                $(OBPRMLIB) $(MATHLIB) #$(CSTKLIB) ${VCLIPLIB} ${RAPIDLIB} ${PQPLIB}
	rm -f main_query.o

#--------------------------------------------------------------------
.SUFFIXES: .cpp
.cpp.o:
	$(CC) ${CFLAGS} -c $<

% : %.o
	$(CXX) $(CXXFLAGS) -o $@ $@.cp $(MATHLIB) $(CSTKLIB) ${VCLIPLIB} ${RAPIDLIB} ${PQPLIB}

#--------------------------------------------------------------------

OBJS = \
	Environment.o \
	FreeBody.o \
	FixedBody.o \
	Connection.o \
	Contact.o \
	DHparameters.o \
	Transformation.o \
	Orientation.o \
	GMSPolyhedron.o \
	Matrix.o \
	Vectors.o \
	Body.o \
	MultiBody.o  \
        Parameters.o \
	Input.o \
        Haptic.o \
        Push.o \
	Cfg.o \
	CfgManager.o \
	Cfg_free.o \
	Cfg_fixed_PRR.o \
	Cfg_free_tree.o \
	Cfg_fixed_tree.o \
	util.o \
	Clock_Class.o \
	Stat_Class.o \
	LocalPlanners.o \
	DistanceMetrics.o \
	CollisionDetection.o \
	GenerateMapNodes.o \
	ConnectMapNodes.o \
	Roadmap.o \
	QueryCmds.o \
	Query.o \
	Weight.o

objs: $(OBJS)

#--------------------------------------------------------------------
runclean::
	rm -f mapnodes.*
	rm -f *.map
	rm -f *.path

clean::
	rm -f query
	rm -f obprm

reallyclean::
	rm -f query
	rm -f obprm
	rm -f libobprm.so
	rm -R -f ii_files
	rm -f *.o
	rm -f so_locations

#-----------------------------------------------------------------------------
# Build and update depent
#-----------------------------------------------------------------------------

Dependencies:
	echo >Dependencies "#-*- Makefile -*-"

include Dependencies

