name: Documentation and Tests

on:
  push:
    branches:
      - release-stage-two
      - github_updates
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: CMake Build
        run: |
          export NOT_ON_C3I=1
          conan install . --output-folder=build --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=false -s build_type=Debug -s compiler.cppstd=gnu17
          cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -B build/
          cmake --build build --target generate_doxygen_docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/Doxygen/html # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}

  # Skipping until tests get reworked in release-stage-two
  # test-job:
  #   needs: build-deploy
  #   runs-on: self-hosted
  #   steps:
  #     - name: Run Tests
  #       run: |
  #         cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -B build/ -DCODE_COVERAGE=ON
  #         cmake --build build --target unit_tests
  #         cmake --build build --target strategy_tests
  #         cd build
  #         ctest --output-on-failure --output-junit junit.xml
